# Generated by Django 3.0.2 on 2020-01-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('born_date', models.DateField(verbose_name='born date')),
                ('dead_date', models.DateField(verbose_name='dead date')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('period', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('creation_date', models.DateField(verbose_name='artwork creation date')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Artist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Category')),
            ],
        ),
    ]
