# Generated by Django 3.0.2 on 2020-02-04 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0002_auto_20200130_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='similar_artworks',
            field=models.ManyToManyField(null=True, related_name='_artwork_similar_artworks_+', to='art.Artwork'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('lead', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('content', models.TextField(null=True)),
                ('artworks', models.ManyToManyField(null=True, to='art.Artwork')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Author')),
            ],
        ),
    ]
