# Generated by Django 3.0.2 on 2020-02-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20200204_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='department',
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(default='sorry, no bio', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='artworks',
            field=models.ManyToManyField(to='art.Artwork'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='similar_artworks',
            field=models.ManyToManyField(related_name='_artwork_similar_artworks_+', to='art.Artwork'),
        ),
    ]
